import { useEffect, useRef, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import {
  ShieldCheck,
  ArrowRight,
  Zap,
  CheckCircle2,
  Lock,
  Key,
  Code2,
  Globe,
  FileCode2,
  Server,
  Eye,
  Activity,
  Layers,
  Search,
  Menu,
  X,
  AlertTriangle,
  RotateCcw
} from 'lucide-react';
import { getSubmission, submitAudit } from '../api/index';
import { Badge, BrandMark, Panel, ScorePill, StatusPill } from '../components/ui';

const GITHUB_REPO_URL = 'https://github.com/nayanrk261/VibeCheck';
const LOCAL_STORAGE_HISTORY_KEY = 'vibecheck_scan_history';

function GithubIcon({ className = "w-4 h-4" }) {
  return (
    <svg className={className} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
      <path d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.403 5.403 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4" />
      <path d="M9 18c-4.51 2-5-2-7-2" />
    </svg>
  );
}

const CAPABILITIES = [
  {
    icon: GithubIcon,
    title: 'Public GitHub Repositories',
    description: 'Instant analysis for public repositories without requiring OAuth permissions or access tokens.'
  },
  {
    icon: Globe,
    title: 'Source + Live Application Audits',
    description: 'Combines static repository code inspection with live endpoint headers and exposure verification.'
  },
  {
    icon: FileCode2,
    title: 'Evidence-backed Findings',
    description: 'Every finding points to concrete line numbers, header responses, or dependency tree records.'
  },
  {
    icon: Activity,
    title: 'Deterministic Security Scoring',
    description: 'Scoring uses mathematical rule weights, keeping scores explainable and repeatable.'
  }
];

const FEATURES = [
  {
    title: 'Fast Audits',
    description: 'Analyze a repository and get actionable security findings without setting up a security pipeline.',
    icon: Zap
  },
  {
    title: 'Evidence First',
    description: 'Findings include source location and supporting evidence instead of vague AI warnings.',
    icon: Eye
  },
  {
    title: 'Deterministic Scoring',
    description: 'Security scores are calculated from deterministic findings, not generated by an LLM.',
    icon: Activity
  },
  {
    title: 'AI Summary',
    description: 'Get a concise executive summary without letting AI invent the underlying findings.',
    icon: FileCode2
  }
];

const HOW_IT_WORKS = [
  {
    step: '01',
    title: 'Provide Repository',
    body: 'Enter a public GitHub repository and optionally provide its live application URL.'
  },
  {
    step: '02',
    title: 'Run Audit',
    body: 'VibeCheck analyzes source files, dependencies, security patterns and live application configuration.'
  },
  {
    step: '03',
    title: 'Get Insights',
    body: 'Review security findings, evidence, scores and an AI-generated executive summary.'
  }
];

const CHECKS = [
  { icon: Key, title: 'Secrets', description: 'Exposed credentials and sensitive tokens' },
  { icon: Layers, title: 'Dependencies', description: 'Known package vulnerabilities' },
  { icon: Lock, title: 'Authentication', description: 'Common authentication and abuse-prevention patterns' },
  { icon: ShieldCheck, title: 'Access Control', description: 'Security-related authorization patterns' },
  { icon: Code2, title: 'Input Validation', description: 'Suspicious unvalidated input usage' },
  { icon: Server, title: 'Security Headers', description: 'CSP, HSTS, X-Frame-Options and related headers' },
  { icon: Globe, title: 'Transport Security', description: 'HTTPS and live endpoint checks' },
  { icon: Eye, title: 'Exposure', description: 'Exposed .env / .git files and similar probes' },
  { icon: Zap, title: 'Performance', description: 'Live response latency' },
  { icon: Activity, title: 'Production Readiness', description: 'SEO, legal and integration signals' }
];

function formatScanDate(dateValue) {
  if (!dateValue) return 'Unknown date';
  const date = new Date(dateValue);
  if (Number.isNaN(date.getTime())) return 'Unknown date';
  return new Intl.DateTimeFormat('en-US', { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' }).format(date);
}

export default function HomePremium() {
  const navigate = useNavigate();
  const formRef = useRef(null);
  const repoRef = useRef(null);
  
  const [repoUrl, setRepoUrl] = useState('');
  const [liveUrl, setLiveUrl] = useState('');
  const [readinessEnabled, setReadinessEnabled] = useState(true);
  const [error, setError] = useState('');
  const [isScanning, setIsScanning] = useState(false);
  const [progress, setProgress] = useState(0);
  const [scanStage, setScanStage] = useState('Preparing audit');
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  
  const [recentScans, setRecentScans] = useState([]);
  const [scansLoading, setScansLoading] = useState(true);
  const [scansError, setScansError] = useState('');
  
  const timerRef = useRef(null);

  // Fetch browser-associated scan history using localStorage submission IDs
  const fetchRecentScans = async () => {
    setScansLoading(true);
    setScansError('');
    try {
      const storedIds = JSON.parse(localStorage.getItem(LOCAL_STORAGE_HISTORY_KEY) || '[]');
      if (!Array.isArray(storedIds) || storedIds.length === 0) {
        setRecentScans([]);
        setScansLoading(false);
        return;
      }

      // Fetch specific submissions in parallel
      const results = await Promise.allSettled(storedIds.map((id) => getSubmission(id)));
      const loadedScans = results
        .filter((res) => res.status === 'fulfilled' && res.value && !res.value.error)
        .map((res) => res.value);

      setRecentScans(loadedScans);
    } catch (err) {
      console.error('Failed to load recent browser scans:', err);
      setScansError('Could not load recent scans. Please try again.');
    } finally {
      setScansLoading(false);
    }
  };

  useEffect(() => {
    fetchRecentScans();
  }, []);

  useEffect(() => () => {
    if (timerRef.current) window.clearInterval(timerRef.current);
  }, []);

  const focusForm = () => {
    formRef.current?.scrollIntoView({ behavior: 'smooth', block: 'center' });
    window.setTimeout(() => repoRef.current?.focus(), 200);
  };

  const startProgress = () => {
    setIsScanning(true);
    setProgress(10);
    setScanStage('Connecting to repository');

    const stages = [
      'Connecting to repository',
      'Loading dependencies',
      'Scanning source files',
      'Checking security rules',
      'Analyzing live endpoints',
      'Preparing findings & AI summary'
    ];
    let index = 0;
    timerRef.current = window.setInterval(() => {
      index += 1;
      if (index < stages.length) {
        setScanStage(stages[index]);
        setProgress((prev) => Math.min(96, prev + 15));
      } else {
        window.clearInterval(timerRef.current);
      }
    }, 500);
  };

  const handleSubmit = async (event) => {
    event.preventDefault();

    if (!repoUrl && !liveUrl) {
      setError('Enter a public GitHub repository or live application URL.');
      return;
    }

    setError('');
    startProgress();

    const cleanRepo = repoUrl.trim().replace(/^https?:\/\/github\.com\//i, '').replace(/^github\.com\//i, '').replace(/\/$/, '');
    let cleanLive = liveUrl.trim();
    if (cleanLive && !cleanLive.startsWith('http')) cleanLive = `https://${cleanLive}`;

    try {
      const result = await submitAudit(
        cleanRepo ? `https://github.com/${cleanRepo}` : '',
        cleanLive || '',
        readinessEnabled ? 'production' : 'core'
      );
      if (timerRef.current) window.clearInterval(timerRef.current);
      setProgress(100);
      setScanStage('Audit complete');

      // Save submissionId in localStorage under vibecheck_scan_history
      const newSubmissionId = result.submissionId || result._id;
      if (newSubmissionId) {
        const storedIds = JSON.parse(localStorage.getItem(LOCAL_STORAGE_HISTORY_KEY) || '[]');
        const updatedIds = [newSubmissionId, ...storedIds.filter((id) => id !== newSubmissionId)].slice(0, 20);
        localStorage.setItem(LOCAL_STORAGE_HISTORY_KEY, JSON.stringify(updatedIds));
      }

      window.setTimeout(() => {
        navigate(`/result/${newSubmissionId}`);
      }, 400);
    } catch (submitError) {
      if (timerRef.current) window.clearInterval(timerRef.current);
      setIsScanning(false);
      setProgress(0);
      setScanStage('Preparing audit');
      setError(
        submitError.response?.data?.error ||
        submitError.response?.data?.details?.[0] ||
        'Audit failed. Please check the repository URL and try again.'
      );
    }
  };

  return (
    <div className="min-h-screen bg-[#050706] text-[#F5F7F6] selection:bg-[#35E59A]/20 selection:text-white">
      {/* Background radial glow & grid texture */}
      <div className="fixed inset-0 pointer-events-none bg-grid-pattern opacity-40 z-0" />
      <div className="fixed top-0 left-1/2 -translate-x-1/2 w-full max-w-7xl h-[600px] pointer-events-none bg-ambient-glow z-0" />

      {/* NAVBAR */}
      <header className="sticky top-0 z-50 border-b border-[rgba(255,255,255,0.08)] bg-[#050706]/80 backdrop-blur-xl">
        <div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-5 lg:px-8">
          <div className="flex items-center gap-8">
            <BrandMark />
            <nav className="hidden items-center gap-6 text-sm text-[#A3AAA7] md:flex">
              <a href="#features" className="transition-colors hover:text-[#F5F7F6]">Features</a>
              <a href="#how-it-works" className="transition-colors hover:text-[#F5F7F6]">How it works</a>
              <a href="#what-we-check" className="transition-colors hover:text-[#F5F7F6]">What We Check</a>
              <a href="#scan-history" className="transition-colors hover:text-[#F5F7F6]">Scan History</a>
            </nav>
          </div>

          <div className="hidden items-center gap-3 md:flex">
            <a
              href={GITHUB_REPO_URL}
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-2 rounded-xl border border-[rgba(255,255,255,0.12)] bg-[#111514] px-3.5 py-2 text-xs font-medium text-[#F5F7F6] transition-colors hover:border-[rgba(255,255,255,0.2)] hover:bg-[#151918]"
            >
              <GithubIcon className="w-4 h-4 text-[#A3AAA7]" />
              GitHub
            </a>
            <button
              type="button"
              onClick={focusForm}
              className="inline-flex items-center gap-1.5 rounded-xl bg-[#35E59A] px-4 py-2 text-xs font-semibold text-[#050706] shadow-[0_0_20px_rgba(53,229,154,0.25)] transition-all hover:bg-[#20C987] hover:shadow-[0_0_25px_rgba(53,229,154,0.4)] cursor-pointer"
            >
              Start Audit
              <ArrowRight className="w-3.5 h-3.5" />
            </button>
          </div>

          {/* Mobile menu trigger */}
          <button
            type="button"
            onClick={() => setMobileMenuOpen(!mobileMenuOpen)}
            className="p-2 text-[#A3AAA7] hover:text-[#F5F7F6] md:hidden"
          >
            {mobileMenuOpen ? <X className="w-6 h-6" /> : <Menu className="w-6 h-6" />}
          </button>
        </div>

        {/* Mobile menu drawer */}
        {mobileMenuOpen && (
          <div className="border-b border-[rgba(255,255,255,0.08)] bg-[#0D1110] px-5 py-4 space-y-3 md:hidden">
            <a href="#features" onClick={() => setMobileMenuOpen(false)} className="block text-sm text-[#A3AAA7] hover:text-[#F5F7F6]">Features</a>
            <a href="#how-it-works" onClick={() => setMobileMenuOpen(false)} className="block text-sm text-[#A3AAA7] hover:text-[#F5F7F6]">How it works</a>
            <a href="#what-we-check" onClick={() => setMobileMenuOpen(false)} className="block text-sm text-[#A3AAA7] hover:text-[#F5F7F6]">What We Check</a>
            <a href="#scan-history" onClick={() => setMobileMenuOpen(false)} className="block text-sm text-[#A3AAA7] hover:text-[#F5F7F6]">Scan History</a>
            <div className="pt-2 flex flex-col gap-2">
              <a
                href={GITHUB_REPO_URL}
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex justify-center items-center gap-2 rounded-xl border border-[rgba(255,255,255,0.12)] bg-[#111514] py-2.5 text-xs font-medium text-[#F5F7F6]"
              >
                <GithubIcon className="w-4 h-4" />
                GitHub
              </a>
              <button
                type="button"
                onClick={() => { setMobileMenuOpen(false); focusForm(); }}
                className="w-full justify-center inline-flex items-center gap-1.5 rounded-xl bg-[#35E59A] py-2.5 text-xs font-semibold text-[#050706]"
              >
                Start Audit →
              </button>
            </div>
          </div>
        )}
      </header>

      <main className="relative z-10">
        {/* HERO SECTION */}
        <section className="mx-auto max-w-7xl px-5 pt-16 pb-12 lg:px-8 lg:pt-24 lg:pb-16 text-center">
          <div className="inline-flex items-center gap-2 rounded-full border border-[rgba(53,229,154,0.3)] bg-[rgba(53,229,154,0.06)] px-3.5 py-1.5 text-xs font-medium text-[#35E59A] shadow-[0_0_20px_rgba(53,229,154,0.1)]">
            <span className="h-2 w-2 rounded-full bg-[#35E59A] animate-pulse" />
            <span>AI App Security Audit</span>
            <span className="text-[#68716D]">|</span>
            <span className="text-[#A3AAA7]">Built for the Vibe Coding Era</span>
            <ArrowRight className="w-3.5 h-3.5 text-[#35E59A]" />
          </div>

          <h1 className="mt-8 text-4xl font-extrabold tracking-tight text-[#F5F7F6] sm:text-6xl lg:text-7xl">
            Build Faster.{' '}
            <span className="text-transparent bg-clip-text bg-gradient-to-r from-[#F5F7F6] via-[#35E59A] to-[#20C987]">
              Ship Safer.
            </span>
          </h1>

          <p className="mx-auto mt-6 max-w-2xl text-base leading-relaxed text-[#A3AAA7] sm:text-lg">
            Security audits for your vibe-coded applications. Get automated, evidence-backed insights to find security issues before you ship.
          </p>

          <div className="mt-8 flex flex-wrap items-center justify-center gap-4">
            <button
              type="button"
              onClick={focusForm}
              className="inline-flex items-center gap-2 rounded-xl bg-[#35E59A] px-6 py-3.5 text-sm font-semibold text-[#050706] shadow-[0_0_30px_rgba(53,229,154,0.3)] transition-all hover:bg-[#20C987] hover:shadow-[0_0_35px_rgba(53,229,154,0.45)] cursor-pointer"
            >
              Start Free Audit
              <ArrowRight className="w-4 h-4" />
            </button>
          </div>

          {/* Subtext Pills */}
          <div className="mt-8 flex flex-wrap items-center justify-center gap-4 text-xs font-medium text-[#A3AAA7]">
            <span className="inline-flex items-center gap-1.5">
              <Zap className="w-3.5 h-3.5 text-[#35E59A]" /> No signup required
            </span>
            <span className="text-[#68716D]">│</span>
            <span className="inline-flex items-center gap-1.5">
              <GithubIcon className="w-3.5 h-3.5 text-[#35E59A]" /> Public repositories only
            </span>
            <span className="text-[#68716D]">│</span>
            <span className="inline-flex items-center gap-1.5">
              <CheckCircle2 className="w-3.5 h-3.5 text-[#35E59A]" /> Results in minutes
            </span>
          </div>
        </section>

        {/* AUDIT FORM & PREVIEW CARDS */}
        <section id="audit-form" className="mx-auto max-w-7xl px-5 py-6 lg:px-8">
          <div className="grid gap-8 lg:grid-cols-12 lg:items-start">
            {/* MAIN AUDIT FORM PANEL (7 cols) */}
            <div className="lg:col-span-7" ref={formRef}>
              <Panel className="p-6 sm:p-8 glow-box-green relative overflow-hidden">
                <div className="border-b border-[rgba(255,255,255,0.08)] pb-5">
                  <h2 className="text-lg font-bold text-[#F5F7F6]">Run Application Audit</h2>
                  <p className="mt-1 text-xs text-[#A3AAA7]">Analyze repository code, dependencies, and endpoint security</p>
                </div>

                <form onSubmit={handleSubmit} className="mt-6 space-y-5">
                  <div>
                    <label className="block text-xs font-semibold uppercase tracking-wider text-[#A3AAA7] mb-2">
                      GitHub Repository <span className="text-[#35E59A]">*</span>
                    </label>
                    <div className="flex items-center rounded-xl border border-[rgba(255,255,255,0.12)] bg-[#070908] px-4 py-3 text-sm transition-colors focus-within:border-[#35E59A]">
                      <input
                        ref={repoRef}
                        type="text"
                        value={repoUrl}
                        onChange={(e) => setRepoUrl(e.target.value)}
                        placeholder="https://github.com/user/project"
                        disabled={isScanning}
                        className="w-full bg-transparent font-mono text-sm text-[#F5F7F6] outline-none placeholder:text-[#68716D] disabled:opacity-50"
                      />
                    </div>
                  </div>

                  <div>
                    <label className="block text-xs font-semibold uppercase tracking-wider text-[#A3AAA7] mb-2">
                      Live Application URL <span className="text-[#68716D]">(optional)</span>
                    </label>
                    <div className="flex items-center rounded-xl border border-[rgba(255,255,255,0.12)] bg-[#070908] px-4 py-3 text-sm transition-colors focus-within:border-[#35E59A]">
                      <span className="mr-2 text-xs font-mono text-[#68716D]">https://</span>
                      <input
                        type="text"
                        value={liveUrl}
                        onChange={(e) => setLiveUrl(e.target.value)}
                        placeholder="app.example.com"
                        disabled={isScanning}
                        className="w-full bg-transparent font-mono text-sm text-[#F5F7F6] outline-none placeholder:text-[#68716D] disabled:opacity-50"
                      />
                    </div>
                  </div>

                  <button
                    type="button"
                    onClick={() => setReadinessEnabled(!readinessEnabled)}
                    className="flex w-full items-center justify-between rounded-xl border border-[rgba(255,255,255,0.08)] bg-[#111514] p-3.5 text-left transition-colors hover:border-[rgba(255,255,255,0.14)] cursor-pointer"
                  >
                    <div>
                      <div className="text-xs font-semibold text-[#F5F7F6]">Include Production Readiness Checks</div>
                      <div className="text-[11px] text-[#A3AAA7]">Check legal, integration signals, and response time metrics</div>
                    </div>
                    <div className={`relative h-5 w-10 rounded-full transition-colors ${readinessEnabled ? 'bg-[#35E59A]' : 'bg-[#151918]'}`}>
                      <span className={`absolute top-0.5 h-4 w-4 rounded-full bg-[#050706] transition-transform ${readinessEnabled ? 'translate-x-5.5' : 'translate-x-0.5'}`} />
                    </div>
                  </button>

                  {error && (
                    <div className="flex items-center gap-2.5 rounded-xl border border-[rgba(255,95,86,0.3)] bg-[rgba(255,95,86,0.08)] p-3.5 text-xs text-[#FF5F56]">
                      <AlertTriangle className="w-4 h-4 shrink-0" />
                      <span>{error}</span>
                    </div>
                  )}

                  <div className="pt-2">
                    <button
                      type="submit"
                      disabled={isScanning}
                      className="w-full inline-flex items-center justify-center gap-2 rounded-xl bg-[#35E59A] py-3.5 text-sm font-bold text-[#050706] shadow-[0_0_25px_rgba(53,229,154,0.3)] transition-all hover:bg-[#20C987] disabled:opacity-60 cursor-pointer"
                    >
                      {isScanning ? (
                        <>
                          <div className="h-4 w-4 rounded-full border-2 border-[#050706] border-t-transparent animate-spin" />
                          <span>{scanStage}... ({progress}%)</span>
                        </>
                      ) : (
                        <>
                          Start Audit
                          <ArrowRight className="w-4 h-4" />
                        </>
                      )}
                    </button>
                  </div>
                </form>

                {/* Progress bar overlay during scan */}
                {isScanning && (
                  <div className="mt-4 pt-3 border-t border-[rgba(255,255,255,0.08)]">
                    <div className="flex justify-between text-xs text-[#A3AAA7] mb-1.5 font-mono">
                      <span>{scanStage}</span>
                      <span>{progress}%</span>
                    </div>
                    <div className="h-1.5 w-full rounded-full bg-[#151918] overflow-hidden">
                      <div
                        className="h-full bg-[#35E59A] transition-all duration-300 rounded-full shadow-[0_0_12px_#35E59A]"
                        style={{ width: `${progress}%` }}
                      />
                    </div>
                  </div>
                )}
              </Panel>
            </div>

            {/* HERO AUDIT PREVIEW CARD (5 cols) */}
            <div className="lg:col-span-5">
              <Panel className="p-6 relative overflow-hidden">
                <div className="flex items-center justify-between border-b border-[rgba(255,255,255,0.08)] pb-4">
                  <div className="flex items-center gap-2">
                    <BrandMark compact />
                    <span className="text-xs font-mono text-[#A3AAA7]">https://github.com/user/project</span>
                  </div>
                  <Badge variant="default" className="text-[10px]">Example audit</Badge>
                </div>

                <div className="mt-5 space-y-2.5 text-xs font-mono">
                  <div className="flex items-center justify-between rounded-lg bg-[#111514] px-3 py-2 text-[#A3AAA7]">
                    <span>Repository discovered</span>
                    <CheckCircle2 className="w-4 h-4 text-[#35E59A]" />
                  </div>
                  <div className="flex items-center justify-between rounded-lg bg-[#111514] px-3 py-2 text-[#A3AAA7]">
                    <span>Dependencies analyzed</span>
                    <CheckCircle2 className="w-4 h-4 text-[#35E59A]" />
                  </div>
                  <div className="flex items-center justify-between rounded-lg bg-[#111514] px-3 py-2 text-[#A3AAA7]">
                    <span>Source files scanned</span>
                    <CheckCircle2 className="w-4 h-4 text-[#35E59A]" />
                  </div>
                  <div className="flex items-center justify-between rounded-lg bg-[#111514] px-3 py-2 text-[#A3AAA7]">
                    <span>Security analysis</span>
                    <CheckCircle2 className="w-4 h-4 text-[#35E59A]" />
                  </div>
                </div>

                <div className="mt-6 rounded-xl border border-[rgba(53,229,154,0.2)] bg-[rgba(53,229,154,0.04)] p-4">
                  <div className="flex items-center justify-between">
                    <div>
                      <div className="text-[10px] font-semibold uppercase tracking-wider text-[#A3AAA7]">Security Score</div>
                      <div className="mt-1 text-4xl font-extrabold font-mono text-[#35E59A]">76</div>
                    </div>
                    <div className="flex flex-col items-end gap-1.5 font-mono text-xs">
                      <span className="rounded-md border border-[rgba(255,95,86,0.3)] bg-[rgba(255,95,86,0.1)] px-2 py-0.5 text-[#FF5F56]">
                        Critical: 3
                      </span>
                      <span className="rounded-md border border-[rgba(255,95,86,0.25)] bg-[rgba(255,95,86,0.08)] px-2 py-0.5 text-[#FF5F56]">
                        High: 8
                      </span>
                      <span className="rounded-md border border-[rgba(255,184,77,0.3)] bg-[rgba(255,184,77,0.1)] px-2 py-0.5 text-[#FFB84D]">
                        Medium: 12
                      </span>
                    </div>
                  </div>
                </div>
              </Panel>
            </div>
          </div>
        </section>

        {/* DASHBOARD PREVIEW SECTION */}
        <section className="mx-auto max-w-7xl px-5 pt-16 pb-8 lg:px-8">
          <div className="text-center mb-8">
            <Badge variant="green">Interactive Dashboard View</Badge>
            <h2 className="mt-3 text-2xl font-bold tracking-tight text-[#F5F7F6] sm:text-3xl">
              Audit Dashboard Overview
            </h2>
            <p className="mt-2 text-xs text-[#A3AAA7]">Sample audit view showing automated evidence aggregation</p>
          </div>

          <div className="rounded-2xl border border-[rgba(255,255,255,0.12)] bg-[#0A0D0C] shadow-2xl overflow-hidden">
            {/* Browser topbar */}
            <div className="flex items-center justify-between border-b border-[rgba(255,255,255,0.08)] bg-[#070908] px-4 py-3">
              <div className="flex items-center gap-2">
                <span className="h-3 w-3 rounded-full bg-[#FF5F56]/80" />
                <span className="h-3 w-3 rounded-full bg-[#FFB84D]/80" />
                <span className="h-3 w-3 rounded-full bg-[#35E59A]/80" />
              </div>
              <div className="rounded-lg bg-[#0D1110] px-4 py-1 text-xs font-mono text-[#68716D] border border-[rgba(255,255,255,0.06)]">
                vibecheck.dev/result/demo-audit-sample
              </div>
              <div className="text-[10px] font-mono text-[#68716D]">Example Audit View</div>
            </div>

            {/* Dashboard Content Grid */}
            <div className="grid md:grid-cols-12 min-h-[380px]">
              {/* Sidebar (3 cols) */}
              <div className="md:col-span-3 border-r border-[rgba(255,255,255,0.08)] bg-[#070908] p-4 space-y-4">
                <div className="pb-3 border-b border-[rgba(255,255,255,0.08)]">
                  <BrandMark compact />
                </div>
                <div className="space-y-1 text-xs font-medium">
                  <div className="flex items-center gap-2.5 rounded-lg bg-[rgba(53,229,154,0.08)] text-[#35E59A] px-3 py-2 border border-[rgba(53,229,154,0.2)]">
                    <Activity className="w-4 h-4" />
                    <span>Security Overview</span>
                  </div>
                  <div className="flex items-center gap-2.5 rounded-lg text-[#A3AAA7] px-3 py-2 hover:bg-[#111514]">
                    <Zap className="w-4 h-4" />
                    <span>Quick Audit</span>
                  </div>
                  <div className="flex items-center gap-2.5 rounded-lg text-[#A3AAA7] px-3 py-2 hover:bg-[#111514]">
                    <Layers className="w-4 h-4" />
                    <span>Scan History</span>
                  </div>
                </div>
              </div>

              {/* Main Preview Area (9 cols) */}
              <div className="md:col-span-9 p-6 space-y-6">
                <div>
                  <h3 className="text-base font-bold text-[#F5F7F6]">Security Overview</h3>
                  <p className="text-xs text-[#A3AAA7]">Your latest audit at a glance.</p>
                </div>

                {/* 4 Metric Cards */}
                <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
                  <div className="rounded-xl border border-[rgba(53,229,154,0.25)] bg-[rgba(53,229,154,0.05)] p-4">
                    <div className="text-[10px] font-semibold uppercase tracking-wider text-[#A3AAA7]">Security Score</div>
                    <div className="mt-1 text-2xl font-bold font-mono text-[#35E59A]">76</div>
                  </div>
                  <div className="rounded-xl border border-[rgba(255,255,255,0.08)] bg-[#0D1110] p-4">
                    <div className="text-[10px] font-semibold uppercase tracking-wider text-[#A3AAA7]">Findings</div>
                    <div className="mt-1 text-2xl font-bold font-mono text-[#FFB84D]">23</div>
                  </div>
                  <div className="rounded-xl border border-[rgba(255,255,255,0.08)] bg-[#0D1110] p-4">
                    <div className="text-[10px] font-semibold uppercase tracking-wider text-[#A3AAA7]">Files Scanned</div>
                    <div className="mt-1 text-2xl font-bold font-mono text-[#F5F7F6]">148</div>
                  </div>
                  <div className="rounded-xl border border-[rgba(255,255,255,0.08)] bg-[#0D1110] p-4">
                    <div className="text-[10px] font-semibold uppercase tracking-wider text-[#A3AAA7]">Dependencies</div>
                    <div className="mt-1 text-2xl font-bold font-mono text-[#8B949E]">42</div>
                  </div>
                </div>

                {/* SVG Trend Chart */}
                <div className="rounded-xl border border-[rgba(255,255,255,0.08)] bg-[#0D1110] p-4">
                  <div className="flex items-center justify-between mb-3 text-xs">
                    <span className="font-semibold text-[#F5F7F6]">Score Stability Trend</span>
                    <span className="font-mono text-[#35E59A]">+4 pts past scans</span>
                  </div>
                  <div className="h-24 w-full">
                    <svg className="w-full h-full" viewBox="0 0 400 80" fill="none">
                      <defs>
                        <linearGradient id="chartGlow" x1="0" y1="0" x2="0" y2="1">
                          <stop offset="0%" stopColor="#35E59A" stopOpacity="0.25" />
                          <stop offset="100%" stopColor="#35E59A" stopOpacity="0" />
                        </linearGradient>
                      </defs>
                      <path d="M0 60 Q 80 45, 160 55 T 320 25 T 400 30 V 80 H 0 Z" fill="url(#chartGlow)" />
                      <path d="M0 60 Q 80 45, 160 55 T 320 25 T 400 30" stroke="#35E59A" strokeWidth="2.5" fill="none" />
                      <circle cx="320" cy="25" r="4" fill="#35E59A" className="animate-ping" />
                      <circle cx="320" cy="25" r="3" fill="#050706" stroke="#35E59A" strokeWidth="2" />
                    </svg>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* CAPABILITY SECTION */}
        <section className="mx-auto max-w-7xl px-5 py-20 lg:px-8">
          <div className="text-center">
            <p className="text-xs font-semibold tracking-widest uppercase text-[#35E59A]">
              BUILT FOR DEVELOPERS WHO SHIP WITH AI
            </p>
            <h2 className="mt-3 text-3xl font-extrabold tracking-tight text-[#F5F7F6] sm:text-4xl">
              Automated, evidence-backed security checks
            </h2>
          </div>

          <div className="mt-12 grid gap-6 sm:grid-cols-2 lg:grid-cols-4">
            {CAPABILITIES.map((cap) => {
              const IconComp = cap.icon;
              return (
                <Panel key={cap.title} hover className="p-6">
                  <div className="grid place-items-center h-10 w-10 rounded-xl border border-[rgba(53,229,154,0.25)] bg-[rgba(53,229,154,0.06)] text-[#35E59A]">
                    <IconComp className="w-5 h-5" />
                  </div>
                  <h3 className="mt-4 text-base font-bold text-[#F5F7F6]">{cap.title}</h3>
                  <p className="mt-2 text-xs leading-relaxed text-[#A3AAA7]">{cap.description}</p>
                </Panel>
              );
            })}
          </div>
        </section>

        {/* FOUR FEATURE HIGHLIGHTS */}
        <section id="features" className="mx-auto max-w-7xl px-5 py-12 lg:px-8 border-t border-[rgba(255,255,255,0.08)]">
          <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-4">
            {FEATURES.map((feat) => {
              const Icon = feat.icon;
              return (
                <Panel key={feat.title} className="p-6">
                  <div className="flex items-center gap-3">
                    <div className="p-2 rounded-lg border border-[rgba(255,255,255,0.12)] bg-[#111514] text-[#35E59A]">
                      <Icon className="w-4 h-4" />
                    </div>
                    <h3 className="text-sm font-bold text-[#F5F7F6]">{feat.title}</h3>
                  </div>
                  <p className="mt-3 text-xs leading-relaxed text-[#A3AAA7]">{feat.description}</p>
                </Panel>
              );
            })}
          </div>
        </section>

        {/* HOW IT WORKS */}
        <section id="how-it-works" className="mx-auto max-w-7xl px-5 py-20 lg:px-8 border-t border-[rgba(255,255,255,0.08)]">
          <Panel className="p-8 sm:p-12 relative overflow-hidden">
            <div className="max-w-xl">
              <span className="text-xs font-semibold tracking-widest uppercase text-[#35E59A]">SIMPLE PROCESS</span>
              <h2 className="mt-2 text-3xl font-extrabold text-[#F5F7F6] sm:text-4xl">How It Works</h2>
              <p className="mt-2 text-sm text-[#A3AAA7]">From repository to security insights in three simple steps.</p>
            </div>

            <div className="mt-12 grid gap-8 md:grid-cols-3">
              {HOW_IT_WORKS.map((step) => (
                <div key={step.step} className="relative rounded-xl border border-[rgba(255,255,255,0.06)] bg-[#111514] p-6">
                  <div className="text-2xl font-black font-mono text-[#35E59A]">{step.step}</div>
                  <h3 className="mt-3 text-lg font-bold text-[#F5F7F6]">{step.title}</h3>
                  <p className="mt-2 text-xs leading-relaxed text-[#A3AAA7]">{step.body}</p>
                </div>
              ))}
            </div>
          </Panel>
        </section>

        {/* WHAT VIBECHECK CHECKS */}
        <section id="what-we-check" className="mx-auto max-w-7xl px-5 py-20 lg:px-8 border-t border-[rgba(255,255,255,0.08)]">
          <div className="text-center mb-12">
            <Badge variant="green">Comprehensive Scanning Engine</Badge>
            <h2 className="mt-3 text-3xl font-extrabold text-[#F5F7F6]">What VibeCheck Checks</h2>
          </div>

          <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5">
            {CHECKS.map((chk) => {
              const Icon = chk.icon;
              return (
                <Panel key={chk.title} hover className="p-4">
                  <div className="flex items-center gap-2.5">
                    <Icon className="w-4 h-4 text-[#35E59A] shrink-0" />
                    <h3 className="text-sm font-bold text-[#F5F7F6]">{chk.title}</h3>
                  </div>
                  <p className="mt-2 text-xs text-[#A3AAA7] leading-snug">{chk.description}</p>
                </Panel>
              );
            })}
          </div>
        </section>

        {/* EVIDENCE SECTION */}
        <section className="mx-auto max-w-7xl px-5 py-20 lg:px-8 border-t border-[rgba(255,255,255,0.08)]">
          <div className="grid lg:grid-cols-12 gap-8 items-center">
            <div className="lg:col-span-5">
              <Badge variant="green">Evidence First</Badge>
              <h2 className="mt-4 text-3xl font-extrabold text-[#F5F7F6] sm:text-4xl leading-tight">
                Don't Just Get a Warning.{' '}
                <span className="text-[#35E59A]">See the Evidence.</span>
              </h2>
              <p className="mt-4 text-sm leading-relaxed text-[#A3AAA7]">
                Every VibeCheck finding is backed by source code line references, file locations, or live HTTP responses. No hallucinations. No guessing.
              </p>
            </div>

            <div className="lg:col-span-7">
              <Panel className="p-6 font-mono">
                <div className="flex items-center justify-between border-b border-[rgba(255,255,255,0.08)] pb-4">
                  <div className="flex items-center gap-3">
                    <span className="rounded-md border border-[rgba(255,95,86,0.3)] bg-[rgba(255,95,86,0.1)] px-2.5 py-1 text-xs font-bold text-[#FF5F56]">
                      HIGH
                    </span>
                    <span className="text-sm font-bold text-[#F5F7F6]">Potential security issue</span>
                  </div>
                  <span className="text-xs text-[#68716D]">Confidence: REVIEW</span>
                </div>

                <div className="mt-4 text-xs text-[#A3AAA7] space-y-1">
                  <div>File: <span className="text-[#35E59A]">client/src/auth/session.js</span></div>
                  <div>Line: <span className="text-[#F5F7F6]">42</span></div>
                </div>

                <div className="mt-4 rounded-xl border border-[rgba(255,255,255,0.08)] bg-[#050706] p-4 text-xs">
                  <pre className="text-[#FFB84D] overflow-x-auto">
{`localStorage.setItem(
  "accessToken",
  token
)`}
                  </pre>
                </div>

                <div className="mt-4 pt-3 border-t border-[rgba(255,255,255,0.08)] text-xs text-[#A3AAA7]">
                  <span className="font-semibold text-[#F5F7F6]">Why it matters:</span> Browser local storage can expose long-lived authentication tokens to JavaScript running in the page.
                </div>
              </Panel>
            </div>
          </div>
        </section>

        {/* SCAN HISTORY SECTION (BROWSER-ASSOCIATED) */}
        <section id="scan-history" className="mx-auto max-w-7xl px-5 py-20 lg:px-8 border-t border-[rgba(255,255,255,0.08)]">
          <div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between mb-8">
            <div>
              <span className="text-xs font-semibold tracking-widest uppercase text-[#35E59A]">SCAN HISTORY</span>
              <h2 className="mt-1 text-2xl font-bold text-[#F5F7F6]">Your Recent Audits</h2>
            </div>
            {recentScans.length > 0 && (
              <StatusPill tone="info">{recentScans.length} {recentScans.length === 1 ? 'scan' : 'scans'} saved in browser</StatusPill>
            )}
          </div>

          {scansLoading ? (
            <div className="space-y-3">
              {[1, 2].map((i) => (
                <div key={i} className="h-16 rounded-2xl border border-[rgba(255,255,255,0.08)] bg-[#0D1110] animate-pulse" />
              ))}
            </div>
          ) : scansError ? (
            <div className="flex items-center justify-between rounded-2xl border border-[rgba(255,95,86,0.3)] bg-[rgba(255,95,86,0.08)] p-5 text-sm text-[#FF5F56]">
              <span>{scansError}</span>
              <button type="button" onClick={fetchRecentScans} className="inline-flex items-center gap-1.5 font-semibold text-xs underline cursor-pointer">
                <RotateCcw className="w-3.5 h-3.5" /> Retry
              </button>
            </div>
          ) : recentScans.length === 0 ? (
            <Panel className="p-10 text-center">
              <Search className="w-10 h-10 text-[#68716D] mx-auto" />
              <h3 className="mt-4 text-base font-bold text-[#F5F7F6]">No audits yet</h3>
              <p className="mt-1 text-xs text-[#A3AAA7]">Run your first security audit to populate your scan history.</p>
              <button
                type="button"
                onClick={focusForm}
                className="mt-5 inline-flex items-center gap-1.5 rounded-xl bg-[#35E59A] px-4 py-2 text-xs font-semibold text-[#050706] cursor-pointer"
              >
                Start Audit →
              </button>
            </Panel>
          ) : (
            <div className="divide-y divide-[rgba(255,255,255,0.08)] overflow-hidden rounded-2xl border border-[rgba(255,255,255,0.08)] bg-[#0D1110]">
              {recentScans.map((scan) => {
                const overallScore = scan.scores?.overall;
                const repoName = scan.repoUrl ? scan.repoUrl.replace(/^https?:\/\/github\.com\//i, '').replace(/\/$/, '') : (scan.liveUrl || 'Audit Submission');
                return (
                  <div
                    key={scan._id}
                    onClick={() => navigate(`/result/${scan._id}`)}
                    className="flex flex-col gap-3 p-4 sm:flex-row sm:items-center sm:justify-between transition-colors hover:bg-[#111514] cursor-pointer"
                  >
                    <div className="space-y-1">
                      <div className="flex items-center gap-2.5">
                        <span className="font-mono text-sm font-semibold text-[#F5F7F6]">{repoName}</span>
                        {scan.auditMode === 'production' && <Badge variant="green" className="text-[9px]">Production</Badge>}
                      </div>
                      <div className="flex flex-wrap items-center gap-2 text-xs text-[#A3AAA7]">
                        <span>{formatScanDate(scan.createdAt)}</span>
                        <span>•</span>
                        <span>{scan.findingsCount || 0} {scan.findingsCount === 1 ? 'finding' : 'findings'}</span>
                      </div>
                    </div>
                    <div className="flex items-center gap-4">
                      <ScorePill value={overallScore} status={scan.auditStatus} />
                      <ArrowRight className="w-4 h-4 text-[#68716D]" />
                    </div>
                  </div>
                );
              })}
            </div>
          )}
        </section>
      </main>

      {/* FOOTER */}
      <footer className="border-t border-[rgba(255,255,255,0.08)] bg-[#070908] py-12 relative z-10">
        <div className="mx-auto grid max-w-7xl gap-8 px-5 lg:grid-cols-12 lg:px-8">
          <div className="lg:col-span-6 space-y-3">
            <BrandMark />
            <p className="text-xs font-semibold text-[#35E59A]">Build. Audit. Ship Safer.</p>
            <p className="max-w-sm text-xs text-[#A3AAA7] leading-relaxed">
              Evidence-first security auditing for AI-built applications.
            </p>
          </div>

          <div className="lg:col-span-2 space-y-3 text-xs">
            <div className="font-semibold uppercase tracking-wider text-[#68716D]">PRODUCT</div>
            <ul className="space-y-2 text-[#A3AAA7]">
              <li><a href="/" className="hover:text-[#F5F7F6]">Home</a></li>
              <li><a href="#features" className="hover:text-[#F5F7F6]">Features</a></li>
              <li><a href="#how-it-works" className="hover:text-[#F5F7F6]">How it works</a></li>
              <li><a href="#what-we-check" className="hover:text-[#F5F7F6]">What We Check</a></li>
              <li><a href="#scan-history" className="hover:text-[#F5F7F6]">Scan History</a></li>
            </ul>
          </div>

          <div className="lg:col-span-2 space-y-3 text-xs">
            <div className="font-semibold uppercase tracking-wider text-[#68716D]">RESOURCES</div>
            <ul className="space-y-2 text-[#A3AAA7]">
              <li>
                <a href={GITHUB_REPO_URL} target="_blank" rel="noopener noreferrer" className="hover:text-[#F5F7F6]">
                  GitHub
                </a>
              </li>
            </ul>
          </div>

          <div className="lg:col-span-2 space-y-3 text-xs">
            <div className="font-semibold uppercase tracking-wider text-[#68716D]">LEGAL</div>
            <ul className="space-y-2 text-[#A3AAA7]">
              <li><a href="/privacy" className="hover:text-[#F5F7F6]">Privacy</a></li>
              <li><a href="/terms" className="hover:text-[#F5F7F6]">Terms</a></li>
              <li><a href="/contact" className="hover:text-[#F5F7F6]">Contact</a></li>
            </ul>
          </div>
        </div>

        <div className="mx-auto max-w-7xl px-5 lg:px-8 pt-8 mt-8 border-t border-[rgba(255,255,255,0.06)] text-center text-xs text-[#68716D]">
          © 2026 VibeCheck. All rights reserved.
        </div>
      </footer>
    </div>
  );
}
